export const liveMatch = {
  tournamentName: "Premier League 2025",
  matchName: "Mumbai Indians vs Chennai Super Kings",
  score: {
    teamA: {
      name: "Mumbai Indians",
      runs: 0,
      wickets: 0,
      overs: 0,
    },
    teamB: {
      name: "Chennai Super Kings",
      runs: 0,
      wickets: 0,
      overs: 0,
    },
  },
  players: {
    teamA: [
      {
        playerName: "Rohit Sharma",
        role: "Batsman",
        status: "Yet to Bat",
        runs: 0,
        balls: 0,
      },
      {
        playerName: "Ishan Kishan",
        role: "Batsman",
        status: "Yet to Bat",
        runs: 0,
        balls: 0,
      },
      {
        playerName: "Suryakumar Yadav",
        role: "Batsman",
        status: "Yet to Bat",
        runs: 0,
        balls: 0,
      },
      {
        playerName: "Cameron Green",
        role: "All-Rounder",
        status: "Yet to Bat",
        runs: 0,
        balls: 0,
        overs: 0,
        wickets: 0,
        runsGiven: 0,
      },
      {
        playerName: "Jasprit Bumrah",
        role: "Bowler",
        status: "Yet to Bowl",
        overs: 0,
        wickets: 0,
        runsGiven: 0,
      },
      {
        playerName: "Piyush Chawla",
        role: "Bowler",
        status: "Yet to Bowl",
        overs: 0,
        wickets: 0,
        runsGiven: 0,
      },
    ],
    teamB: [
      {
        playerName: "MS Dhoni",
        role: "Batsman",
        status: "Yet to Bat",
        runs: 0,
        balls: 0,
      },
      {
        playerName: "Ruturaj Gaikwad",
        role: "Batsman",
        status: "Yet to Bat",
        runs: 0,
        balls: 0,
      },
      {
        playerName: "Shivam Dube",
        role: "All-Rounder",
        status: "Yet to Bat",
        runs: 0,
        balls: 0,
        overs: 0,
        wickets: 0,
        runsGiven: 0,
      },
      {
        playerName: "Deepak Chahar",
        role: "Bowler",
        status: "Yet to Bowl",
        overs: 0,
        wickets: 0,
        runsGiven: 0,
      },
      {
        playerName: "Ravindra Jadeja",
        role: "All-Rounder",
        status: "Yet to Bowl",
        overs: 0,
        wickets: 0,
        runsGiven: 0,
      },
      {
        playerName: "Matheesha Pathirana",
        role: "Bowler",
        status: "Yet to Bowl",
        overs: 0,
        wickets: 0,
        runsGiven: 0,
      },
    ],
  },
};
