export const fakeData = [
  {
    matchId: 1,
    team1: 1,
    team2: 2,
    matchName: "Mumbai vs Chennai",
    tournamentName: "Spring Champion 2025",
    result: "Mumbai Wins",
  },
  {
    matchId: 2,
    team1: 3,
    team2: 4,
    matchName: "Delhi vs Bangalore",
    tournamentName: "Spring Champion 2025",
    result: "Bangalore Wins",
  },
  {
    matchId: 3,
    team1: 5,
    team2: 6,
    matchName: "Hyderabad vs Kolkata",
    tournamentName: "Summer Cup 2025",
    result: "Kolkata Wins",
  },
  {
    matchId: 4,
    team1: 1,
    team2: 3,
    matchName: "Mumbai vs Delhi",
    tournamentName: "Spring Champion 2025",
    result: "Draw",
  },
  {
    matchId: 5,
    team1: 2,
    team2: 5,
    matchName: "Chennai vs Hyderabad",
    tournamentName: "Autumn League 2025",
    result: "Chennai Wins",
  },
  {
    matchId: 6,
    team1: 6,
    team2: 4,
    matchName: "Kolkata vs Bangalore",
    tournamentName: "Autumn League 2025",
    result: "Bangalore Wins",
  },
  {
    matchId: 7,
    team1: 1,
    team2: 6,
    matchName: "Mumbai vs Kolkata",
    tournamentName: "Final Clash 2025",
    result: "Kolkata Wins",
  },
  {
    matchId: 8,
    team1: 3,
    team2: 5,
    matchName: "Delhi vs Hyderabad",
    tournamentName: "Final Clash 2025",
    result: "Hyderabad Wins",
  },
  // Repeats across older tournaments
  {
    matchId: 9,
    team1: 1,
    team2: 2,
    matchName: "Mumbai vs Chennai",
    tournamentName: "Spring Champion 2024",
    result: "Chennai Wins",
  },
  {
    matchId: 10,
    team1: 3,
    team2: 4,
    matchName: "Delhi vs Bangalore",
    tournamentName: "Monsoon Trophy 2024",
    result: "Delhi Wins",
  },
  {
    matchId: 11,
    team1: 1,
    team2: 3,
    matchName: "Mumbai vs Delhi",
    tournamentName: "Legacy League 2023",
    result: "Mumbai Wins",
  },
  {
    matchId: 12,
    team1: 5,
    team2: 6,
    matchName: "Hyderabad vs Kolkata",
    tournamentName: "Legends Cup 2023",
    result: "Hyderabad Wins",
  },
];

export const matchStats = [
  {
    matchId: 1,
    stats: {
      matchDetails: {
        matchName: "Mumbai vs Chennai",
        result: "Mumbai Wins",
        tournamentName: "Spring Champion 2025",
        team1Name: "Mumbai",
        team2Name: "Chennai",
      },
      team1: [
        {
          firstName: "Rohit",
          playerName: "Rohit Sharma",
          role: "Batsman",
          teamName: "Mumbai",
          runs: 85,
          wicket: null,
        },
        {
          firstName: "Jasprit",
          playerName: "Jasprit Bumrah",
          role: "Bowler",
          teamName: "Mumbai",
          runs: 10,
          wicket: 3,
        },
        {
          firstName: "Suryakumar",
          playerName: "Suryakumar Yadav",
          role: "Batsman",
          teamName: "Mumbai",
          runs: 45,
          wicket: null,
        },
        {
          firstName: "Ishan",
          playerName: "Ishan Kishan",
          role: "Wicketkeeper",
          teamName: "Mumbai",
          runs: 30,
          wicket: null,
        },
        {
          firstName: "Hardik",
          playerName: "Hardik Pandya",
          role: "All-Rounder",
          teamName: "Mumbai",
          runs: 40,
          wicket: 2,
        },
        {
          firstName: "Trent",
          playerName: "Trent Boult",
          role: "Bowler",
          teamName: "Mumbai",
          runs: 5,
          wicket: 4,
        },
      ],
      team2: [
        {
          firstName: "MS",
          playerName: "MS Dhoni",
          role: "Batsman",
          teamName: "Chennai",
          runs: 60,
          wicket: null,
        },
        {
          firstName: "Deepak",
          playerName: "Deepak Chahar",
          role: "Bowler",
          teamName: "Chennai",
          runs: 5,
          wicket: 2,
        },
        {
          firstName: "Ravindra",
          playerName: "Ravindra Jadeja",
          role: "All-Rounder",
          teamName: "Chennai",
          runs: 30,
          wicket: 1,
        },
        {
          firstName: "Ruturaj",
          playerName: "Ruturaj Gaikwad",
          role: "Batsman",
          teamName: "Chennai",
          runs: 70,
          wicket: null,
        },
        {
          firstName: "Dwayne",
          playerName: "Dwayne Bravo",
          role: "All-Rounder",
          teamName: "Chennai",
          runs: 25,
          wicket: 3,
        },
        {
          firstName: "Moeen",
          playerName: "Moeen Ali",
          role: "All-Rounder",
          teamName: "Chennai",
          runs: 35,
          wicket: 1,
        },
      ],
    },
  },
  {
    matchId: 2,
    stats: {
      matchDetails: {
        matchName: "Delhi vs Bangalore",
        result: "Bangalore Wins",
        tournamentName: "Spring Champion 2025",
        team1Name: "Delhi",
        team2Name: "Bangalore",
      },
      team1: [
        {
          firstName: "Shikhar",
          playerName: "Shikhar Dhawan",
          role: "Batsman",
          teamName: "Delhi",
          runs: 50,
          wicket: null,
        },
        {
          firstName: "Kagiso",
          playerName: "Kagiso Rabada",
          role: "Bowler",
          teamName: "Delhi",
          runs: 10,
          wicket: 2,
        },
        {
          firstName: "Rishabh",
          playerName: "Rishabh Pant",
          role: "Wicketkeeper",
          teamName: "Delhi",
          runs: 40,
          wicket: null,
        },
        {
          firstName: "Prithvi",
          playerName: "Prithvi Shaw",
          role: "Batsman",
          teamName: "Delhi",
          runs: 30,
          wicket: null,
        },
        {
          firstName: "Axar",
          playerName: "Axar Patel",
          role: "All-Rounder",
          teamName: "Delhi",
          runs: 20,
          wicket: 1,
        },
        {
          firstName: "Anrich",
          playerName: "Anrich Nortje",
          role: "Bowler",
          teamName: "Delhi",
          runs: 5,
          wicket: 3,
        },
      ],
      team2: [
        {
          firstName: "Virat",
          playerName: "Virat Kohli",
          role: "Batsman",
          teamName: "Bangalore",
          runs: 80,
          wicket: null,
        },
        {
          firstName: "AB",
          playerName: "AB de Villiers",
          role: "Batsman",
          teamName: "Bangalore",
          runs: 60,
          wicket: null,
        },
        {
          firstName: "Yuzvendra",
          playerName: "Yuzvendra Chahal",
          role: "Bowler",
          teamName: "Bangalore",
          runs: 5,
          wicket: 2,
        },
        {
          firstName: "Devdutt",
          playerName: "Devdutt Padikkal",
          role: "Batsman",
          teamName: "Bangalore",
          runs: 40,
          wicket: null,
        },
        {
          firstName: "Mohammed",
          playerName: "Mohammed Siraj",
          role: "Bowler",
          teamName: "Bangalore",
          runs: 10,
          wicket: 3,
        },
        {
          firstName: "Glenn",
          playerName: "Glenn Maxwell",
          role: "All-Rounder",
          teamName: "Bangalore",
          runs: 50,
          wicket: 1,
        },
      ],
    },
  },
  {
    matchId: 3,
    stats: {
      matchDetails: {
        matchName: "Hyderabad vs Kolkata",
        result: "Kolkata Wins",
        tournamentName: "Summer Cup 2025",
        team1Name: "Hyderabad",
        team2Name: "Kolkata",
      },
      team1: [
        {
          firstName: "David",
          playerName: "David Warner",
          role: "Batsman",
          teamName: "Hyderabad",
          runs: 70,
          wicket: null,
        },
        {
          firstName: "Bhuvneshwar",
          playerName: "Bhuvneshwar Kumar",
          role: "Bowler",
          teamName: "Hyderabad",
          runs: 10,
          wicket: 2,
        },
        {
          firstName: "Kane",
          playerName: "Kane Williamson",
          role: "Batsman",
          teamName: "Hyderabad",
          runs: 50,
          wicket: null,
        },
        {
          firstName: "Rashid",
          playerName: "Rashid Khan",
          role: "All-Rounder",
          teamName: "Hyderabad",
          runs: 30,
          wicket: 3,
        },
        {
          firstName: "Manish",
          playerName: "Manish Pandey",
          role: "Batsman",
          teamName: "Hyderabad",
          runs: 40,
          wicket: null,
        },
        {
          firstName: "T Natarajan",
          playerName: "T Natarajan",
          role: "Bowler",
          teamName: "Hyderabad",
          runs: 5,
          wicket: 2,
        },
      ],
      team2: [
        {
          firstName: "Shubman",
          playerName: "Shubman Gill",
          role: "Batsman",
          teamName: "Kolkata",
          runs: 80,
          wicket: null,
        },
        {
          firstName: "Andre",
          playerName: "Andre Russell",
          role: "All-Rounder",
          teamName: "Kolkata",
          runs: 60,
          wicket: 2,
        },
        {
          firstName: "Sunil",
          playerName: "Sunil Narine",
          role: "Bowler",
          teamName: "Kolkata",
          runs: 10,
          wicket: 3,
        },
        {
          firstName: "Nitish",
          playerName: "Nitish Rana",
          role: "Batsman",
          teamName: "Kolkata",
          runs: 50,
          wicket: null,
        },
        {
          firstName: "Pat",
          playerName: "Pat Cummins",
          role: "Bowler",
          teamName: "Kolkata",
          runs: 20,
          wicket: 4,
        },
        {
          firstName: "Eoin",
          playerName: "Eoin Morgan",
          role: "Batsman",
          teamName: "Kolkata",
          runs: 40,
          wicket: null,
        },
      ],
    },
  },
  {
    matchId: 4,
    stats: {
      matchDetails: {
        matchName: "Mumbai vs Delhi",
        result: "Draw",
        tournamentName: "Spring Champion 2025",
        team1Name: "Mumbai",
        team2Name: "Delhi",
      },
      team1: [
        {
          firstName: "Rohit",
          playerName: "Rohit Sharma",
          role: "Batsman",
          teamName: "Mumbai",
          runs: 50,
          wicket: null,
        },
        {
          firstName: "Jasprit",
          playerName: "Jasprit Bumrah",
          role: "Bowler",
          teamName: "Mumbai",
          runs: 5,
          wicket: 2,
        },
        {
          firstName: "Suryakumar",
          playerName: "Suryakumar Yadav",
          role: "Batsman",
          teamName: "Mumbai",
          runs: 30,
          wicket: null,
        },
        {
          firstName: "Ishan",
          playerName: "Ishan Kishan",
          role: "Wicketkeeper",
          teamName: "Mumbai",
          runs: 20,
          wicket: null,
        },
        {
          firstName: "Hardik",
          playerName: "Hardik Pandya",
          role: "All-Rounder",
          teamName: "Mumbai",
          runs: 25,
          wicket: 1,
        },
        {
          firstName: "Trent",
          playerName: "Trent Boult",
          role: "Bowler",
          teamName: "Mumbai",
          runs: 10,
          wicket: 3,
        },
      ],
      team2: [
        {
          firstName: "Shikhar",
          playerName: "Shikhar Dhawan",
          role: "Batsman",
          teamName: "Delhi",
          runs: 60,
          wicket: null,
        },
        {
          firstName: "Kagiso",
          playerName: "Kagiso Rabada",
          role: "Bowler",
          teamName: "Delhi",
          runs: 5,
          wicket: 2,
        },
        {
          firstName: "Rishabh",
          playerName: "Rishabh Pant",
          role: "Wicketkeeper",
          teamName: "Delhi",
          runs: 40,
          wicket: null,
        },
        {
          firstName: "Prithvi",
          playerName: "Prithvi Shaw",
          role: "Batsman",
          teamName: "Delhi",
          runs: 30,
          wicket: null,
        },
        {
          firstName: "Axar",
          playerName: "Axar Patel",
          role: "All-Rounder",
          teamName: "Delhi",
          runs: 20,
          wicket: 1,
        },
        {
          firstName: "Anrich",
          playerName: "Anrich Nortje",
          role: "Bowler",
          teamName: "Delhi",
          runs: 5,
          wicket: 3,
        },
      ],
    },
  },
];
